<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>AccountNumber</name>
   <tag></tag>
   <elementGuidId>068864a2-22d1-452b-82b3-44d090c3689c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dash&quot;]/div[8]/div[1]/div[1]/div/div/div[2]/dl/dd[1]</value>
   </webElementProperties>
</WebElementEntity>
