<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>REST_Object</name>
   <tag></tag>
   <elementGuidId>324beb14-459c-4ceb-9fb9-3b98bb7b530f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <httpBody>{&quot;PerformDiagnosticsRequestCplxType&quot;:{&quot;accountIdentification&quot;:{&quot;siteReference&quot;:10,&quot;accountNumber&quot;:400673001},&quot;channelName&quot;:&quot;Trinity&quot;,&quot;serviceCategory&quot;:[{&quot;serviceCategoryCode&quot;:&quot;D&quot;,&quot;responseRequired&quot;:true},{&quot;serviceCategoryCode&quot;:&quot;C&quot;,&quot;responseRequired&quot;:true}]}}</httpBody>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-service</name>
      <type>Main</type>
      <value>GetCPEDiagnostics</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-conversationID</name>
      <type>Main</type>
      <value>uuid:f61d4fae-7dec-11d0-a765-00a0c91e6bf8</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-operation</name>
      <type>Main</type>
      <value>PerformDiagnostics</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-senderURI</name>
      <type>Main</type>
      <value>MIDDLEWARE</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-requestID</name>
      <type>Main</type>
      <value>uuid:f61d4fae-7dec-11d0-a765-00a0c91e6bf8P1</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-userid</name>
      <type>Main</type>
      <value>TRINITYMOBILE</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-originatorURI</name>
      <type>Main</type>
      <value>Trinity</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-requestTimestamp</name>
      <type>Main</type>
      <value>2017-08-22T22:55:46.224+01:00</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>content-type</name>
      <type>Main</type>
      <value>application/json; charset=utf-8</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-version</name>
      <type>Main</type>
      <value>uuid:f61d4fae-7dec-11d0-a765-00a0c91e6bf8</value>
   </httpHeaderProperties>
   <httpHeaderProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>VMMD-messageID</name>
      <type>Main</type>
      <value>uuid:f81d4fae-8jan-22e5-a765-00a0c91e7ee7-0001</value>
   </httpHeaderProperties>
   <restParameters>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>postId</name>
      <type>Main</type>
      <value>1</value>
   </restParameters>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>http://fmw-wb-t14:8080/ejb/restapi/GetCPEDiagnostics/performDiagnostics</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceFunction></soapServiceFunction>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
